Role.create(character_name:'Sherlock Holmes')
Role.create(character_name:'Captain Ahab')
Role.create(character_name:'Jessica Jones')
Audition.create(actor:'Robert Downey Jr', location:'Santa Monica', phone:8495453434, hired:true, role_id:1)
Audition.create(actor:'Bobert Downer Jr', location:'Beverly Hills', phone:499, hired:true, role_id:1)
Audition.create(actor:'Willem Dafoe', location:'Palm Springs', phone:834993483, hired:true, role_id:2)
Audition.create(actor:'Will Smith', location:'Santa Monica', phone:3, hired:false, role_id:2)
Audition.create(actor:'Laura Boebert', location:'DC', phone:999, hired:false, role_id:3)
Audition.create(actor:'Rebekah Shaw', location:'Colorado Springs', phone:303030300, hired:false, role_id:3)